### ISSUE TITLE
is there any reason why you only have .pyc in here?

### ISSUE THREAD

**Issue by arnaudmkonan** [trangnm58/D3NER#1]
i was trying to test this and compare it to CliNER but it doesn't seem to be open at all.
it also doesn't work `RuntimeError: Bad magic number in .pyc file`

**Comment by trangnm58** [comment]
I'm sorry for the inconvenient. My supervisor only allows me to upload ".pyc" files publicly.
Please state your email below so I can send you the source code if that's ok with you.

**Comment by arnaudmkonan** [comment]
Thank you for getting back to me.
My email is arnaudmkonan@gmail.com
Thank you
